- name: "Add the user '{{geyser.user}}' with a bash shell, appending the group 'sudo' to the user's groups"
  ansible.builtin.user:
    name: {{geyser.user}}
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Download geyser.jar from download api
  ansible.builtin.get_url:
    url: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
    dest: "{{geyser.installation_path}}/standalone.jar"
    mode: '0700'
- name: Template a file to {{geyser.installation_path}}/config.yml
  ansible.builtin.template:
    src: /templates/config.yml.j2
    dest: "{{geyser.installation_path}}/config.yml"
    owner: {{geyser.user}}
    group: {{geyser.user}}
    mode: '0700'
- name: Template a file to /etc/systemd/system/{{geyser.name}}.service
  ansible.builtin.template:
    src: /templates/geyser.service.j2
    dest: /etc/systemd/system/{{geyser.name}}.service
    owner: {{geyser.user}}
    group: {{geyser.user}}
    mode: '0700'
  notify: 
    - Start geyser