---
- name: "Add the user geyser with a bash shell, appending the group 'sudo' to the user's groups"
  ansible.builtin.user:
    name: "{{ geyser.user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present
  tags: add_user

- name: Download geyser.jar from download api
  ansible.builtin.get_url:
    url: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
    dest: "{{ geyser.installation_path }}/standalone.jar"
    mode: '0700'
  tags: download_geyser

- name: Template a file to installtion path ./config.yml
  ansible.builtin.template:
    src: /templates/config.yml.j2
    dest: "{{ geyser.installation_path }}/config.yml"
    owner: "{{ geyser.user }}"
    group: "{{ geyser.user }}"
    mode: '0700'
  tags: config_geyser

- name: Template a file to /etc/systemd/system/geyser.service
  ansible.builtin.template:
    src: /templates/geyser.service.j2
    dest: /etc/systemd/system/{{ geyser.name }}.service
    owner: "{{ geyser.user }}"
    group: "{{ geyser.user }}"
    mode: '0700'
  notify: 
    - Start geyser
  tags: systemd_geyser

- name: Restart geyser
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: "{{ geyser.name }}"
  tags: restart_geyser